### ISSUE TITLE
Formula doesn't work properly

### ISSUE THREAD

**Issue by sinowitabc** [kogalur/randomForestSRC#101]
Hi! I just found that the survival analysis function ignores some formula operators and returns the same results. Or did I misunderstand something?

Example:
```
library(survival)
library(randomForestSRC)
data("vdv", package = "randomForestSRC")

set.seed(123)
rfsrc(Surv(Time, Censoring) ~ Z31560 + Z34893, vdv) 

set.seed(123)
rfsrc(Surv(Time, Censoring) ~ Z31560 - Z34893, vdv) 

set.seed(123)
rfsrc(Surv(Time, Censoring) ~ Z31560 : Z34893, vdv) 

```
Same output:
Sample size: 78
                    Number of deaths: 34
                     Number of trees: 1000
           Forest terminal node size: 15
       Average no. of terminal nodes: 2.995
No. of variables tried at each split: 2
              Total no. of variables: 2
       Resampling used to grow trees: swor
    Resample size used to grow trees: 49
                            Analysis: RSF
                              Family: surv
                      Splitting rule: logrank *random*
       Number of random split points: 10
                    (OOB) Error rate: 55.2989791%

**Comment by ishwaran** [comment]
This is by intention.  Because this is a nonparametric method the formula only represents *which* variables are to be included in the model fit and now *how* they will be included.  We do it this way because trees are invariant to monotone transformations on the features. Therefore it is pointless to take minus a variable or log of a variable.  It also creates issues with test data. We used to have a comment about this in the help file but took it out since many users now understand how random forests works.  If you want to manipulate the data to have interactions (as in your third example), then you need to manipulate the data frame before hand and then include the interaction in your formula.

**Comment by sinowitabc** [comment]
Thank you! I got it. 😄
