### ISSUE TITLE
Prediction issue when there is no missing value in training set, but testing set contains missing. 

### ISSUE THREAD

**Issue by ThomasZhang717** [kogalur/randomForestSRC#112]
Hi,

I am curious whether we have security mechanism of missing values, when training set has no missing values but testing set has? I use this package, and have a trial. When this situation happens, the R session returns an error and restart. I have tried to add `na.impute` in `rfsrc` and `predict.rfsrc`, but it is not worked.

**Comment by ishwaran** [comment]
Hi,

I think I see what you are saying.  Can you verify that the following is the situation that you mean?

I use the pbc data set for illustration.  I create training data without missing values and test data with missing values
```
> data(pbc, package = "randomForestSRC")
> trn=na.omit(pbc[1:312,])
> tst=pbc[313:418,]
```

I fit the training data and try to predict using test data.

```
> predict(o, tst)
Error in finalizeData(fnames, newdata, na.action) : 
  no records in the NA-processed data: consider using 'na.action=na.impute'
```

This happens because `na.action="na.omit" `is set by default.   This causes missing data to be removed and by doing so, there is nothing left.  Next, and I think this is the issue you are alluding to, when I set` na.action="na.impute"` I get a segfault and the code crashes:

```
> predict(o, tst, na.action="na.impute")

 *** caught segfault ***
address 0xf8, cause 'memory not mapped'

```
We will look into this issue and respond back shortly.
