### ISSUE TITLE
Displaying sample tree

### ISSUE THREAD

**Issue by dbarg1** [kogalur/randomForestSRC#40]
Hi - is there a way to display one of the trees in the forest ? I'm able to get the split statistics on the variables using the stat.split function, but I'm having a little trouble parsing what an actual tree looks like.

Thanks.

**Comment by kogalur** [comment]
There are probably a few routines out there that will parse a tree, but you have to massage our particular output into a format that is compatible with the particular plotting routine you deploy.  All the information is in the output object $forest$nativeArray. Try the following example:

set.seed(-1)
seed = -1
library("randomForestSRC")
data("veteran", package = "randomForestSRC")

vet.obj <- rfsrc(Surv(time, status) ~ ., data = veteran, ntree = 1, bootstrap = "none", mtry = 6, nodedepth = 3, seed=seed)


One way to view the forest is to examine

> vet.obj$forest$nativeArray

and

> vet.objforest$nativeFactorArray

They are recursively parsed arrays. You can see in the example that
there are no factor splits ($nativeFactorArray = null). The first row
in $nativeArray is depicting a split on parmID = 3 at contPt = 40. The
next row is a split of the left daughter of the node depicted in the
previous row. Here we split on parmID = 5 at contPt = 53. The next row
is again the left daughter of the row in the previous row.  Note that
parmID = 0, indicating it is a terminal node.  Row 4 is the right
daughter of the parent node in row 2.  The split is on parmID = 4, and
the split point is contPT = 11.  Row 5 and 6 show that the daughter
nodes to Row 4 are terminal.  You can see that this array can be
parsed by a recursive routine. For factor splits, we output the HEX
code for the split.  High bits go left and low bits go right, much the
same way as <= go left and > go right.  The nodeID is not unique
because of the recursive nature of the algorithm.  Only the terminal
nodeID are unique because that's all we really care about at the end
of the day. We always split left first, and the left nodeID assumes
the parent nodeID.  Only when that node terminates, do we split right,
and increment the nodeID.

You should be able to massage this output to your needs.  Thanks.

**Comment by dbarg1** [comment]
Thank you for the detailed explanation ! 

I was able to convert it to a "network" data frame (as required by the data.tree package) by iterating through the rows and creating an edge list.

The data.tree package then can convert this "network" into their tree data type , and has lots of functions for traversing and plotting the tree.

**Comment by dbarg1** [comment]
Now, by the way - can an output tree have leaves containing 0 uncensored cases ?
I am seeming to be getting some leaves that contain 0 uncensored cases, but several censored ones.

Is this allowed by the algorithm?

**Comment by kogalur** [comment]
If you wish, and if you think it's appropriate, you can send your conversion algorithm our way, and we'll include it as an R-function in the package.  We'll credit you, of course.  Alternatively, you could find some other way to make it available to the public.  It seems like a useful function, as we've had this question before.  

As for censoring, it is completely possible for a split to produce a node where all cases in a daughter are censored (0).  This daughter is, by definition, terminal.

**Comment by dbarg1** [comment]
Hello - I can of course provide it for you - it would be useful to have in the package. Give me a little time to prepare it for readability.

What is the best way to send the code to you ?

**Comment by kogalur** [comment]
You could just send us the R and (hopefully Rd) file(s).  If you wanted to completely test them, you could clone the source code provided here (on GitHub), splice them into the package, and follow the instructions at https://kogalur.github.io/randomForestSRC/,  and the menu item "Building for R ...".  Thanks!

**Comment by dbarg1** [comment]
I've attached the code for the function. It's self contained, and hopefully well-documented. I had trouble generating the Rd file for the function, but I have the roxygen style comments included before the function definition.
[displaying_sample_tree.zip](https://github.com/kogalur/randomForestSRC/files/3404110/displaying_sample_tree.zip)

**Comment by dbarg1** [comment]
Hello - I just wanted to follow up - have you had a chance to test out the function ?

**Comment by kogalur** [comment]
I'm so sorry for the delayed response. We were on vacation and lost you through the cracks after we got back. We haven't had a chance yet to look at the code, but look forward to reviewing it and getting back to you. Thanks again!

**Comment by Yue-Jiang** [comment]
Just to second this, it would be awesome if we can have a function to extract a single tree similar to randomForest::getTree() and ranger::treeInfo(). Thanks!

**Comment by coreysparks** [comment]
Agreed with @Yue-Jiang this function would be a nice addition

**Comment by msaadati** [comment]
I agree that this would be a nice addition. 

@dbarg1 Thanks for sharing your code! Unfortunately running the example you provided, I get an error:
 "Error: `n()` must only be used inside dplyr verbs."
Any ideas?

**Comment by kogalur** [comment]
The function get.tree is has been added in 2.10.0.  Please see the manual for further information.  Thanks to @dbarg1 for prototyping this for us.
