### ISSUE TITLE
rfsrc: Family assigned surv-CR when it is supposed to be surv

### ISSUE THREAD

**Issue by vfincke** [kogalur/randomForestSRC#414]
Hey there, 

I am trying to build a random forest for survival with right censored data. In my data table I have numeric values for 100 variables, the status (V1, coded as 0=alive, 1=dead) and the OS in years (V2). When doing: 
> rfModel <- rfsrc(Surv(V2, V1) ~.,
+                         data = dataS,
+                         importance = TRUE)

the output gives Family: surv-CR, although this is supposed to be a normal survival forest. 
Can you tell me, what is going on here? I did not find an option to set the family manually. 

Thanks in advance and best wishes, 

Victoria 

Here the full output: 
> print(rfModel)
                         Sample size: 81
                    Number of events: 36, 45
                     Number of trees: 500
           Forest terminal node size: 15
       Average no. of terminal nodes: 3.486
No. of variables tried at each split: 10
              Total no. of variables: 100
       Resampling used to grow trees: swor
    Resample size used to grow trees: 51
                            Analysis: RSF
                              Family: surv-CR
                      Splitting rule: logrankCR *random*
       Number of random split points: 10
   (OOB) Requested performance error: 0.47142857, 0.41818182

**Comment by ishwaran** [comment]
I believe your censoring variable "V1" is a factor with levels 0 and 1.  The code is converting this to a numeric value which are values 1 and 2 which then triggers a competing risk analysis where there are 2 competing risks (and no censored data as you can see by the fact that number of events sum to the total sample size 81).

I am moving to discussion since this is not an issue.
